### ISSUE TITLE
Error Message about "leafo/scssphp" upon installation

### ISSUE THREAD

**Issue by mgrn0** [featdd/minifier#1]
I get an error message in the backend upon trying to install the "minifier" extension in it's current version:

PHP: 5.6.27
TYPO3: 6.2.25 
Minifier ext: 0.9.6 
OS: MacOS with MAMP Pro

Whenever I try to activate the extension in the extension manager, I get the following error message: "The package "minifier" depends on "leafo/scssphp" which is not present in the system."

![screenshot 2016-11-03 at 9 29 56 am](https://cloud.githubusercontent.com/assets/3019226/19959597/46023834-a1a8-11e6-8313-ebdb735677ed.png)

typo3temp and caches cleared, but error remains, extension is not active. I moved the zip Version of the extension into the typo3conf/ext, but same behaviour. What could I have done wrong?

Michael

**Comment by featdd** [comment]
hm can't reproduce this on my dev machine, do you use typo3 in composer mode?

**Comment by mgrn0** [comment]
nope, standard (local) clone of a TYPO3 installation. What can I do to help? Maybe a case-sensitive issue? (Folder/Class names)?

**Comment by featdd** [comment]
the problem seems to be the composer.json, having the named lib as dependency declared...
I have to make investigatements if typo3 in non/composer mode is parsing this and throws this error cause its no typo3 extension...

**Comment by mgrn0** [comment]
if I can do something to help pinpoint this issue, please let me know - anytime!

**Comment by mgrn0** [comment]
Tried to install 0.9.7 of the minifier extension todat and the error persists (although it shows already before activating it):

![screenshot 2016-11-07 at 8 03 19 am](https://cloud.githubusercontent.com/assets/3019226/20049034/d2cd100c-a4c0-11e6-8e97-c3546fc4ca33.png)

when I remove the "requires" section in the composer file, installation succeeds without problem.

**Comment by featdd** [comment]
still could'nt reproduce this...

did you try uninstall, delete the extension, clear typo3temp, etc....?

**Comment by mgrn0** [comment]
yes, of course. the only way I could get it to install was to remove the dependencies section in the composer file (which was sufficient for me). thanks for having looked into this, maybe I am a real edge case ;)
